import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="mx-auto w-full max-w-[960px] px-4 py-4">
          <p className="font-bold">Satyam</p>
        </header>
        <main className="mx-auto w-full max-w-[960px] flex-1 px-4 py-8">
          {children}
        </main>
        <footer className="mx-auto w-full max-w-[960px] px-4 py-8">
          <p>Built with Next.js, TypeScript and Tailwind CSS.</p>
        </footer>
      </body>
    </html>
  );
}
