import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeToggle from "@/components/ThemeToggle";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeScript = `
  try {
    var t = localStorage.getItem("theme");
    if (t === "light" || t === "dark") {
      document.documentElement.dataset.theme = t;
    }
  } catch (e) {}
`;

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body className="min-h-full flex flex-col">
        <header className="mx-auto flex w-full max-w-[960px] items-center justify-between px-4 py-4">
          <p className="font-bold">Satyam</p>
          <ThemeToggle />
        </header>
        <main className="mx-auto w-full max-w-[960px] flex-1 px-4 py-8">
          {children}
        </main>
        <footer className="mx-auto w-full max-w-[960px] px-4 py-8">
          <p>Built with Next.js, TypeScript and Tailwind CSS.</p>
        </footer>
      </body>
    </html>
  );
}
